=== rodrigodelama/pfat_p23_24/xml/libros.dtd
<!ELEMENT books (book+)>

<!ELEMENT book (title, authors, year, pages, genres)>
<!ATTLIST book
          index CDATA #IMPLIED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT pages (#PCDATA)>

<!ELEMENT authors (author+)>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author 
    name CDATA #REQUIRED
    nationality CDATA #IMPLIED>

<!ELEMENT genres (genre+)>
<!ELEMENT genre (#PCDATA)>

=== rodrigodelama/pfat_p23_24/xml/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "file:./libros.dtd">

<books>
    <book index="1">
        <title><![CDATA[Don Quixote]]></title>
        <authors>
            <author name="Miguel de Cervantes" nationality="Spanish"></author>
        </authors>
        <year>1605</year>
        <pages>3218 </pages>
        <genres>
            <genre><![CDATA[Novel]]></genre>
            <genre><![CDATA[Satire]]></genre>
            <genre><![CDATA[Psychological Fiction]]></genre>
        </genres>
    </book>
</books>
