=== rodrigodelama/pfat_p23_24/xml/movies.dtd
<!ELEMENT movies (movie+)>

<!ELEMENT movie (title, director, year, duration, actors, genres, nationalities)>
<!ATTLIST movie
          index CDATA #IMPLIED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT duration (#PCDATA)>

<!ELEMENT actors (actor+)>
<!ELEMENT actor (#PCDATA)>
<!ATTLIST actor character CDATA #REQUIRED>

<!ELEMENT genres (genre+)>
<!ELEMENT genre (#PCDATA)>

<!ELEMENT nationalities (nationality+)>
<!ELEMENT nationality (#PCDATA)>

=== rodrigodelama/pfat_p23_24/xml/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM "file:./movies.dtd">

<movies>
    <movie index="1">
        <title><![CDATA[El Padrino]]></title>
        <director><![CDATA[Francis Ford Coppola]]></director>
        <year>1972</year>
        <duration>175</duration>
        <actors>
            <actor character="Vito Corleone"><![CDATA[Marlon Brando]]></actor>
            <actor character="Michael Corleone"><![CDATA[Al Pacino]]></actor>
        </actors>
        <genres>
            <genre><![CDATA[Drama]]></genre>
            <genre><![CDATA[Crime]]></genre>
        </genres>
        <nationalities>
            <nationality><![CDATA[Estados Unidos]]></nationality>
        </nationalities>
    </movie>
</movies>
